services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    image: lucaplawliet/audiobot:latest
    environment:
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_GEMINI_MODEL=${GOOGLE_GEMINI_MODEL}
      - TRANSCRIPTION_ENGINE=${TRANSCRIPTION_ENGINE}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: always
