name: Build and deploy Docker image to Docker Hub and Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_REPO: lucaplawliet/audiobot
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $DOCKER_REPO:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $DOCKER_REPO:$IMAGE_TAG

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update App Service to use Docker image
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: audiobot-webapp
          images: ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
